### ISSUE TITLE
Problem with the classifier

### ISSUE THREAD

**Issue by nbargues** [DeniRibicic/q2ONT#1]
Hi, 

I try to use your pipeline. First I try to launch q2ONT with a previous SILVA 132 classifier used for my previous Illumina work; but I have an error:

> Plugin error from feature-classifier:
 The scikit-learn version (0.19.1) used to generate this artifact does not match the current version of scikit-learn installed (0.21.2). Please retrain your classifier for your current deployment to prevent data-corruption errors.

So I try to generate a new classifier with the new conda env. But it seems to process for nothing.
Do you have a copy of the one that you use ?

Regards

**Comment by DeniRibicic** [comment]
Hi again @nbargues.
Basically you need to train the classifier with the same version of scikilt-learn, therefore qiime2 as the one you are using to run the pipeline.
But I guess you have figured that out by now.

**Comment by nbargues** [comment]
Train a classifier need a lot of CPUs and memory. Also, your tmp/ directory need to have a lot of volume (>100Go). Cheers
