### ISSUE TITLE
Need help to create a barplot of the q2ONT results.

### ISSUE THREAD

**Issue by langse62171** [DeniRibicic/q2ONT#4]
First of all thank you for the q2ONT script! Since I am relatively new to bioinformatics this is a great help for me.
I have run your q2ONT pipeline with our Nanopore data of a 16S sequencing. Importing the ONT data, training the classifier with the SILVA database and the rest of the pipeline worked well, the following data was generated from the basecalled data: 
1_total_run.fastq.gz
2_demux-reads (folder)
3_QC (folder)
4_single-end-demux.qza
4_single_end-demux.qzv
5_derep-seqs.qza
5_derep-seqs.qzv
5_derep-table.qza
5_derep-table.qzv
6.1_uchime-ref-out (folder)
6.2_new-ref-seqs-op_ref-85.qza
6.2_rep-seqs-op_ref-85.qza
6.2_table-op_ref-85.qza
7_aligned-filtered_derep-seqs.qza
8_masked-aligned-filtered_derep-seqs.qza
9_unrooted-tree.qza
10_rooted-tree.qza
11_taxonomy-sklearn.qza

and exported:
dna-sequences.fasta
feature-table.biom
table-with-taxonomy.biom
taxonomy.tsv
tree.nwk

Now I'm searching for a way to visualize the results in barplots. I have already installed phyloseq, but I don't quite understand how to generate a barplot with the files I received. Could you please show me a way to do this with phyloseq?
I also tried to visualize the results with the qiime visualizer and iTol but I have some problems with these options, maybe you can help me with that too.
When I try to create a barplot of the data with the qiime taxa barplot visualizer (https://docs.qiime2.org/2019.10/plugins/available/taxa/barplot/). I would use as input Artifact Table the file "6.2_table-op_ref-85.qza" and as input Artifact taxonomy the file "11_taxonomy-sklearn.qza". Are these the correct files? But I also need a metadata file. Could you tell me how to generate it in qiime from the above data. 
I also uploaded the file "10_rooted-tree.qza" to iTol (https://itol.embl.de/) to visualize the results, but unfortunately the tool only shows the tree with the OTU-IDs and not with the taxa. Maybe you know how I get the taxa here. 
If you need more information please let me know.
Thank you a lot!

**Comment by DeniRibicic** [comment]
@langse62171 I have already replied at q2 forum, but here it is again:

> Now I want to create a barplot of the data with the qiime taxa barplot visualizer (https://docs.qiime2.org/2019.10/plugins/available/taxa/barplot/). I would use as input Artifact Table the file “6.2_table-op_ref-85.qza” and as input Artifact taxonomy the file “11_taxonomy-sklearn.qza”. Are these the correct files?

Yes, those are correct ones!

> But I also need a metadata file. Can someone please tell me how to generate it from the above data.

The metadata file should contain sample identifiers in the first column, named as #SampleID. Sample identifiers are the names of your samples, which should correspond to ONT barcodes, e.g. BC01, BC02, etc… Then you can add more columns describing your samples = metadata.

I’d also suggest to explore @MaestSi nanopore 16S pipeline [MetONTIIME](https://github.com/MaestSi/MetONTIIME), which is more flexible and up to date.

**Comment by DeniRibicic** [comment]
@langse62171 
I'll close the ticket now, since you have managed to figure it out :)
For others, see [here](https://forum.qiime2.org/t/need-help-to-create-a-barplot-of-my-data-with-the-qiime-taxa-barplot-visualizer/13993/4).
