### ISSUE TITLE
Unable to run q20NT.sh in Qiime2core 

### ISSUE THREAD

**Issue by miguensblanco** [DeniRibicic/q2ONT#5]
Hi Deni,

Thanks for this pipeline. I find it great and straightforward but if I am writing this is because I have an small issue. 
I think I have all the artefacts ready and the script downloaded in my working directory and then I run:
`/home/qiime2/q2ONT.sh [-i 0_basecalled-fastq] [-j SILVA_132_QIIME_release/rep_set/rep_set_all/99/silva_132_99_16S_sequence.qza] [-c silva-132-99-nb-classifier.qza] [-t 2] ` 

Inmediately after running the script I got the next message:

`concatenating .fastq files...
cat: '/*.fastq': No such file or directory

all fastq files merged!

demultiplexing and trimming reads
could not find cpp_functions.so - please reinstall
demultiplexing failed!!!

/home/qiime2/q2ONT.sh: line 96: cd: 2_demux-reads: No such file or directory`

Probably I am doing something wrong with this line of code or with my sequences,etc.

Anyway, I would appreciate any help.

Best,

Jesús

**Comment by DeniRibicic** [comment]
@miguensblanco 
First- your `q2ONT.sh` script should be in a path, meaning in whichever directory you are  you should be able to call the script without typing full path to it (see [point 1](https://github.com/DeniRibicic/q2ONT#how-to-use) ).

Second- when you are running the script your commands (flags, i.e `-i`, `-j`, etc..) should not be in square brackets. In `README.md` description this is only for the purpose of explanation what should be called by each flag. This also means after you remove the brackets and type the flag (e.g.` -i`) you should be able to call each file using tab completion option.

Let me know how it works out.

**Comment by miguensblanco** [comment]
Thanks for your help, actually I manage to run the script but I keep getting some errors down the pipeline:
**First error I can see:**
concatenating .fastq files...
cat: '/home/qiime2/q2ONT.sh/*.fastq': Not a directory

all fastq files merged!

demultiplexing and trimming reads
could not find cpp_functions.so - please reinstall
demultiplexing failed!!!

**Next one**
/home/qiime2/q2ONT.sh: line 106: cd: 3_QC: No such file or directory
mv: cannot stat '*-trimmed': No such file or directory
mv: cannot stat '*.fastq': No such file or directory
gzip: *.fastq: No such file or directory

**Third :**
activating QIIME2...
Could not find conda environment: qiime2-2019.10
You can list all discoverable environments with `conda info --envs`.

qiime2-2019.10 active
looking for input files ...

wrong format. Check your .fastq filenames!!!
reads FAILED TO IMPORT!!!

I keep getting errors until the very end, I was trying also to fix a problem I got during the installation of Porechop where I keep getting the message: -error: [Errno 2] No such file or directory: 'porechop/cpp_functions.so' I am not sure that it is related to the problem with q2ONT but I also rise an issue at their place,just in case.

I really appreciate your help, cheers.

**Comment by DeniRibicic** [comment]
@miguensblanco 
First error that you get should be self-explanatory, meaning that you haven't specified correct folder where your `.fastq` files are located. As a matter of fact you seem to use the script itself `q2ONT.sh` as a folder??
All the errors following are the product of the very first error, since the script uses output from previous steps as input for the next ones. 
What can also be seen from the first error is that you have some trouble with `Porechop` installation and it seems it's not properly installed.
Also, there is an indication from the third error that your `conda q2` environment is not properly created/installed.

In couple of days I will actually change the workflow of **q2ONT** and some of the elements will be substituted with new ones, e.g Porechop with Guppy

**Comment by miguensblanco** [comment]
Thanks! There was something weird, yes. I am not an expert but I can understand that a script is not a folder :). I think I was trying to gather many files and folders in a common folder it was not a good way to do it. I was running it again and I am getting stacked at this point now:

```
`concatenating .fastq files...`


`all fastq files merged!
`

demultiplexing and trimming reads
could not find cpp_functions.so - please reinstall
demultiplexing failed!!!


/home/qiime2/q2ONT/q2ONT.sh: line 96: cd: 2_demux-reads: No such file or  directory
```

I think the problem is with the Porechop (looking forward for the Guppy addition thoug), I will try yo overpass the _cpp_function_ problem somehow but I appreciate any feedback!

**Comment by DeniRibicic** [comment]
Hi again @miguensblanco,
Yes, this is straight a `Porechop` error, has to do something with bad installation.
Have you tried to install it through [conda env](https://anaconda.org/bioconda/porechop)?

**Comment by miguensblanco** [comment]
Hi! Yes, it took me a while and it's all good now, sorry. Now looks to be working smoothly up to the point of _screening for chimeric sequences..._. I left it before went to sleep last night and it was there this morning, no error message nothing but just not getting further. I restart the script this morning and it's more than a hour since I got to the same point and not further progress.


```
activating QIIME2...
Could not find conda environment: qiime2-2019.10
You can list all discoverable environments with `conda info --envs`.


qiime2-2019.10 active
looking for input files ...

using '3_QC' folder to import reads ...
Imported 3_QC as CasavaOneEightSingleLanePerSampleDirFmt to 4_single-end-demux.qza
reads successfully imported as '.qza' file!


preparing visualization file ...
Saved Visualization to: 4_single-end-demux.qzv


dereplicating sequences...
Saved FeatureTable[Frequency] to: 5_derep-table.qza
Saved FeatureData[Sequence] to: 5_derep-seqs.qza
sequences successfully dereplicated!


generating visualization files...
Saved Visualization to: 5_derep-seqs.qzv
Saved Visualization to: 5_derep-table.qzv


screening for chimeric sequences...

```


Thanks!

**Comment by DeniRibicic** [comment]
@miguensblanco this step will take usually really long time to run (depending on input) and it is very memory intensive. In case there are no errors and the script is "hanging" you are most likely out of RAM.
One option here would be to use Silva db clustered at lower threshold than 99%, which you probably use here.

**Comment by miguensblanco** [comment]
It took around 24 hours but the screening for chimeric sequences it was succesful and the OTU clustering too. Problem was the sequence aligment with maffit.

```
Plugin error from alignment:

  Command '['mafft', '--preservecase', '--inputorder', '--thread', '1', '/tmp/qiime2-archive-2joqrgmx/1b8fb7c8-8aa0-4c22-b174-1d17e222eecd/data/dna-sequences.fasta']' returned non-zero exit status 1.

Debug info has been saved to /tmp/qiime2-q2cli-err-wi1fm6f5.log
sequences FAILED to ALIGN!!!
FAILED to MASK and FILTER OUT highly variable positions!!!
FAILED TO GENERATE un-rooted tree!!!
FAILED TO GENERATE rooted tree!!!
```
Aferwards went ahead to assign taxonomy but I got several errros after the one mention above:

```
Plugin error from feature-classifier:

  Unable to allocate 6.67 GiB for an array with shape (895664128,) and data type float64

Debug info has been saved to /tmp/qiime2-q2cli-err-o9qkfxx_.log
taxonomy FAILED TO ASSIGN!!!
```
Sorry for the long message, I have read online that maffit issue is related to the RAM memory I have allocated in the Virtual Box. I currently have 4096 MB, I could go up to 8 but that would endanger my laptop life span. There is a known RAM that I need to run maffit? I could use remotely the computer or the server (not that easy the server access at the moment) from my College.

Also, could I start somehow to run my script from the point where it failed? How? 

I really appreciate your help and **patience**!

**Comment by DeniRibicic** [comment]
@miguensblanco both errors are due to insufficient RAM. While MAFFT is a known bottleneck in the workflow, taxonomy assignment is less so. Just for the purpose of comparison, I have available about 100 GB of RAM and MAFFT will fail sometimes with this workflow. However, when it comes to taxonomy assignment using trained classifier, there is no problem to run it on my cluster. 4GB that you have is not really enough to do it, so I would advise to connect to your university server and run it there. 
Alternatively, as advised before, you can use classifier trained on Silva db clustered at lower threshold than 99%. That should save some RAM.

In regard to running the workflow from a specific point, you can easily read it from `q2ONT.sh` script. Just open it in a text editor and you can see each step that is being performed. Then just continue step-by-step using separate commands and paste them to your terminal.

Anyways, as already mentioned I am rewriting the workflow, and a lot of steps are going to be changed. E.g. no chimera step, different type of OTU clustering approach, different approach to phylogeny step and different approach to taxonomy assignment. 
These changes will speed up the whole workflow and should be also less RAM intensive.

**Comment by miguensblanco** [comment]
@DeniRibicic Thanks! I was getting access for a server, looks like it has around 64 GB and I already manage to install all I need, I am looking for how to get access to a different server but in the mean time I'd try this.

About where to start the run of the script, I am about to show how low are my skills here. What I would do is: I open the script in a text editor and I would copy and paste from 

```
#aligning sequences
if [ -f "6.2_rep-seqs-op_ref-85.qza" ]; then
echo ""
echo ""
echo "OTU clustering successful!"
echo ""
echo ""
echo "sequence alignment with mafft..."
qiime alignment mafft \
--i-sequences 6.2_rep-seqs-op_ref-85.qza \
--o-alignment 7_aligned-filtered_derep-seqs.qza
else
echo "OTU clustering FAILED!!!"
fi
```
etc
I should paste the commands changing the working directory to the q2ONT file where all the previous files were generated? Should I am not write before the` q2ONT.sh [-i fastq_directory] [-j reference_seqs] [-c classifier] [-t threads]` command to indicate how many threads,etc. Sorry about my lack of knowledge here, thanks again!

**Comment by DeniRibicic** [comment]
@miguensblanco 
This is what you use:
```
qiime alignment mafft \
--i-sequences 6.2_rep-seqs-op_ref-85.qza \
--o-alignment 7_aligned-filtered_derep-seqs.qza
```
You should already have the input file in your folder `6.2_rep-seqs-op_ref-85.qza`, just continue from there.
Before you start you need to activate q2 environment: `conda activate qiime2-<whichever version you have>`

**Comment by miguensblanco** [comment]
@DeniRibicic Thanks! I was playing a bit with the script and now it was running for about an hour. I just trim the parts of the script that I did before:

![Running](https://user-images.githubusercontent.com/38765973/79378314-028d8c00-7f55-11ea-8e55-80c6172c8b66.jpg)

What you would do? Let it run or just abort it and do it with the piece of code that you just sent me?
Thanks again!

**Comment by DeniRibicic** [comment]
An hour is nothing, if the chimera step was for 24h this will even go longer I am afraid. 
But I wouldn't expect too much, this will likely run out of memory. How much of data do you have actually?

**Comment by miguensblanco** [comment]
I know, I was saying that at least it did not give an error as soon as I run the script. RAM memory should be 64 Gb. Around that level the server would kill off the job with the Out of Memory message. The server is a public one for medical research in UK but I'd try to run in the College one that it's much powerful but more difficult to work remotely.
Thanks!

**Comment by miguensblanco** [comment]
![Error q2ONT](https://user-images.githubusercontent.com/38765973/79562498-2232ca80-80a3-11ea-9a2d-2394ce64df43.jpg)
@DeniRibicic  After almost 24h run I got this message. It does not explain very well what the error is but googling a bit looks like have something to do with the memory. Is that right? I'd try then with the server of my College and see how it goes.
Thanks!
Jesús

**Comment by DeniRibicic** [comment]
@miguensblanco it's exactly indicated where the debug info is saved. If you look into that file you should be able to see what the issue was. Most likely, as you said, is memory related

**Comment by miguensblanco** [comment]
@DeniRibicic  Hi again and thanks for all your help, when previously runnning I got this message at the very beginning of the alignment with mafft (I attach the whole file, just in case)

```
inputfile = orig
115766 x 1400 - 1400 d
nthread = 1
stacksize: 8192 kb->22610 kb
generating a scoring matrix for nucleotide (dist=200) ... done
Gap Penalty = -1.53, +0.00, +0.00


 /home/ubuntu/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/skbio/io/registry.py:548: FormatIdentificationWarning: <_io.BufferedReader name='/tmp/q2-AlignedDNAFASTAFormat-ci0pm4yo'> does not look like a fasta file
  % (file, fmt), FormatIdentificationWarning)
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/qi
[qiime2-q2cli-err-2nvwkpt1.log](https://github.com/DeniRibicic/q2ONT/files/4533983/qiime2-q2cli-err-2nvwkpt1.log)
ime2-2019.7/lib/python3.6/site-packages/q2cli/commands.py", line 328, in __call__
    results = action(**arguments)
  File "</home/ubuntu/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/decorator.py:decorator-gen-477>", line 2, in mafft
  File "/home/ubuntu/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/sdk/action.py", line 240, in bound_callable
    output_types, provenance)
  File "/home/ubuntu/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/sdk/action.py", line 383, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/ubuntu/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/q2_alignment/_mafft.py", line 94, in mafft
```
 I think this is not related to the memory issue since it keep going until it fail, but should I be concern? As I said, it does not stop the run but looks like there is a jump in the numbers during the alignment (attached file)
 
Sorry for all the questions in the last weeks and thank you very much!!
Jesús

**Comment by DeniRibicic** [comment]
@miguensblanco I have never encountered such an error before. However, what I can read from it seems that you have fed a wrong type of a file to this step. Have you run this automatically with q2ONT script or did you do manually step-by step?
The q2ONT is merely a script wrapping up bunch of commands mostly from q2 pipeline, but also from some other bioinformatic tools. If all the tools are installed properly, there should be no errors coming up.

**Comment by miguensblanco** [comment]
@DeniRibicic yes, I just run the mafft part of the script. I think I had installed all the other packages and qiime2 did not give me any warning or error. I am using tmux to run it, may have any incidence?

Update: I run it again and  during hours the .log file does not show any error at the point where it is shown in the  one I attached before, it just show the same error when it fails after +/- 24 hours, so do you think that indicates it is a memory issue or there is something else? 
I attach the last log file that I got when I rerun this step
[qiime2-q2cli-err-0s6ue35wlast log .log](https://github.com/DeniRibicic/q2ONT/files/4545031/qiime2-q2cli-err-0s6ue35wlast.log.log)


Thanks!

**Comment by miguensblanco** [comment]
Hi @DeniRibicic 
I hope you are doing alright, I am trying to allocate the pipeline for the ONT samples. I am getting there with the memory for the last steps. But I am also getting some issues in the new server, have you seen a mistake like the ones attached? Looks there is an issue with Trimmomatic right?


![3](https://user-images.githubusercontent.com/38765973/81238329-b2f12c00-8ff9-11ea-9ab4-d159531ea646.png)
![4](https://user-images.githubusercontent.com/38765973/81238333-b389c280-8ff9-11ea-8275-d6c03b63156c.png)

Thanks! 

Jesús

**Comment by DeniRibicic** [comment]
Hi @miguensblanco,

Yes, it seems that there is a problem with running trimmomatic. I haven't encounter this, but I guess a simple google search will get you there.

**Comment by langse62171** [comment]
Hi Deni, 
i didn't want to open a new thread because of this, just asking if you can already tell when the above mentioned update of the pipeline will be ready?  I'm very excited about that.
Best regards, 
Sebastian

**Comment by miguensblanco** [comment]
Hi @DeniRibicic , thanks for your help all the way! I finished yesterday, great relief. A question about the outcome though, there is a file or a way to check the error rate of my reads?? Thanks!

**Comment by DeniRibicic** [comment]
@miguensblanco what do you mean by error rate?

**Comment by DeniRibicic** [comment]
@langse62171 I have it already in place more or less, however need some time to write up README section properly.
I am quite busy now, but hope to be able to deploy it by June.

**Comment by miguensblanco** [comment]
Hi @DeniRibicic . I was finishing my previous run and it worked alright. Now I am trying to run from the beginning another run from my lab. I'd like to ask you, which approach you'd take if you have too many reads (I left the run for far too long) . I was wondering if I should rise the trimmomatic values or if there is a another way to reduce the overload number of reads that I have. 

Otherwise, If I polish the number of reads with Guppy with the EPI2MEA can I introduce somehow them later in the q2ONT script?

Thanks once again!

Jesus

**Comment by DeniRibicic** [comment]
@miguensblanco I would use all the reads normally to assign taxonomy. Just for the phylogenetic analysis (as we already discussed that mafft-aligning part is bottleneck) I would do sub-sampling to a certain number of reads.
That is actually one of the novelty a new pipeline will have.

I'll close this issue now, since it's not related to original inquiry. If you have any specific questions please open a new tread for it.
